module.exports = Object.freeze({
  NO_TOKEN: "NO_ACCESS_TOKEN",
  TOKEN_INVALID: "ACCESS_TOKEN_INVALID",
  TOKEN_BLACKLISTED: "ACCESS_TOKEN_BLACKLISTED",
  TOKEN_EXPIRED: "ACCESS_TOKEN_EXPIRED",
  NO_TOKEN: "NO_TOKEN",
  REFRESH_TOKEN_ERROR: "REFRESH_TOKEN_ERROR (NOT FOUND IN DB)",

  EMAIL_UNAVAILABLE: "EMAIL_UNAVAILABLE",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
});
